services:
  php:
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}      # Version de PHP à utiliser (définie dans .env)
    env_file: 
      - .env                      # Charge les variables (ex: XDEBUG_MODE)
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}        # Active/désactive Xdebug (ex: "off" par défaut)
    volumes:
      - ../src:/var/www/html            # Monte le code source de l'application
      - ./php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini:ro    # Configuration PHP custom
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini:ro    # Configuration Xdebug custom

  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    volumes:
      - ../src:/var/www/html:ro
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "${APP_PORT}:80"                        # Expose le port 80 HTTP

  mysql:
    build:
      context: ./mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    profiles: ["mysql"]
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"                   # Expose MySQL sur le port 3306

  postgres:
    build:
      context: ./postgres
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    profiles: ["postgres"]
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"                  # Expose PostgreSQL sur le port 5432

  mongo:
    build:
      context: ./mongo
      args:
        MONGO_VERSION: ${MONGO_VERSION}
    profiles: ["mongo"]
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"               # Expose MongoDB sur le port 27017

  redis:
    build:
      context: ./redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    env_file:
      - .env
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"                 # Expose Redis sur le port 6379

  mysql_test:
    build:
      context: ./mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    profiles: ["mysql"]
    env_file:
      - .env
    volumes:
      - mysql_test_data:/var/lib/mysql
    ports:
      - "${MYSQL_TEST_PORT}:3306"

  postgres_test:
    build:
      context: ./postgres
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    profiles: ["postgres"]
    env_file:
      - .env
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_TEST_PORT}:5432"

  mongo_test:
    build:
      context: ./mongo
      args:
        MONGO_VERSION: ${MONGO_VERSION}
    profiles: ["mongo"]
    env_file:
      - .env
    volumes:
      - mongo_test_data:/data/db
    ports:
      - "${MONGO_TEST_PORT}:27017"

  adminer:
    image: adminer:4.8.1
    restart: no
    ports:
      - "${ADMINER_PORT}:8080"
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "${PORT_MAIL_SMTP}:1025"
      - "${PORT_MAIL_HTTP}:8025"

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}-management
    ports:
      - ${PORT_RABBITMQ_LISTENER}:5672
      - ${PORT_RABBITMQ_TCP_LISTENER}:5673
      - ${PORT_RABBITMQ_MANAGEMENT}:15672

volumes:
  mysql_data:
  postgres_data:
  mongo_data:
  redis_data:
  mysql_test_data:
  postgres_test_data:
  mongo_test_data:
